USE [master]
GO

IF  NOT EXISTS (SELECT name FROM [master].[dbo].[sysdatabases] WHERE name = N'@DATABASE')
BEGIN
	CREATE DATABASE [@DATABASE]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'@DATABASE', FILENAME = N'@FILE_PATH\@DATABASE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	 LOG ON 
	( NAME = N'@DATABASE_log', FILENAME = N'@FILE_PATH\@DATABASE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	
	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	BEGIN
		EXEC [@DATABASE].[dbo].[sp_fulltext_database] @action = 'enable'
	END
	
	ALTER DATABASE [@DATABASE] SET ANSI_NULL_DEFAULT OFF 
	ALTER DATABASE [@DATABASE] SET ANSI_NULLS OFF 
	ALTER DATABASE [@DATABASE] SET ANSI_PADDING OFF 
	ALTER DATABASE [@DATABASE] SET ANSI_WARNINGS OFF 
	ALTER DATABASE [@DATABASE] SET ARITHABORT OFF 
	ALTER DATABASE [@DATABASE] SET AUTO_CLOSE ON 
	ALTER DATABASE [@DATABASE] SET AUTO_SHRINK OFF 
	ALTER DATABASE [@DATABASE] SET AUTO_UPDATE_STATISTICS ON 
	ALTER DATABASE [@DATABASE] SET CURSOR_CLOSE_ON_COMMIT OFF 
	ALTER DATABASE [@DATABASE] SET CURSOR_DEFAULT  GLOBAL 
	ALTER DATABASE [@DATABASE] SET CONCAT_NULL_YIELDS_NULL OFF 
	ALTER DATABASE [@DATABASE] SET NUMERIC_ROUNDABORT OFF 
	ALTER DATABASE [@DATABASE] SET QUOTED_IDENTIFIER OFF 
	ALTER DATABASE [@DATABASE] SET RECURSIVE_TRIGGERS OFF 
	ALTER DATABASE [@DATABASE] SET  ENABLE_BROKER 
	ALTER DATABASE [@DATABASE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	ALTER DATABASE [@DATABASE] SET DATE_CORRELATION_OPTIMIZATION OFF 
	ALTER DATABASE [@DATABASE] SET TRUSTWORTHY OFF 
	ALTER DATABASE [@DATABASE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	ALTER DATABASE [@DATABASE] SET PARAMETERIZATION SIMPLE 
	ALTER DATABASE [@DATABASE] SET READ_COMMITTED_SNAPSHOT ON 
	ALTER DATABASE [@DATABASE] SET HONOR_BROKER_PRIORITY OFF 
	ALTER DATABASE [@DATABASE] SET RECOVERY SIMPLE 
	ALTER DATABASE [@DATABASE] SET  MULTI_USER 
	ALTER DATABASE [@DATABASE] SET PAGE_VERIFY CHECKSUM  
	ALTER DATABASE [@DATABASE] SET DB_CHAINING OFF 
	ALTER DATABASE [@DATABASE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	ALTER DATABASE [@DATABASE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	ALTER DATABASE [@DATABASE] SET  READ_WRITE 
END


